# Generated by Django 5.2.6 on 2025-09-18 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del negocio')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Código postal debe tener exactamente 5 dígitos')], verbose_name='Código postal')),
                ('niche', models.CharField(max_length=100, verbose_name='Nicho de negocio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessNiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del nicho')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nicho de negocio',
                'verbose_name_plural': 'Nichos de negocio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'Código postal debe tener exactamente 5 dígitos')], verbose_name='Código postal')),
                ('niche', models.CharField(max_length=100, verbose_name='Nicho de negocio')),
                ('results_count', models.IntegerField(default=0, verbose_name='Número de resultados')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='exports/', verbose_name='Archivo Excel generado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de búsqueda',
                'verbose_name_plural': 'Historial de búsquedas',
                'ordering': ['-created_at'],
            },
        ),
    ]
