# Generated by Django 5.2.6 on 2025-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_api_key_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='country',
            field=models.CharField(default='ES', max_length=2),
        ),
    ]
